name: Build CLI Base
on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build-cli-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # Without this option, we don't get the tag information
        with:
          fetch-depth: 0

      - name: Initialise the build system
        run: |
          chmod u+x $GITHUB_WORKSPACE/build/bin/*.sh
          $GITHUB_WORKSPACE/build/bin/initbuild.sh
          source $GITHUB_WORKSPACE/build/bin/.functions.sh

      # 4. CLI container image
      # -------------------------------------------------------------------------------------------
      - name: Build the docker image
        run: |
          $GITHUB_WORKSPACE/build/bin/docker-build.sh -n ibmmas -i cli-base
          docker tag ibmmas/cli-base quay.io/ibmmas/cli-base:${{ env.DOCKER_TAG }}

      # https://github.com/marketplace/actions/push-to-registry
      - name: Push the docker image
        id: push_to_quay
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: quay.io/ibmmas/cli-base:${{ env.DOCKER_TAG }}
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
