name: Build CLI Base
'on':
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
env:
  CRYPTO_VERSION: 43.0.0
  WHEELS_URL: >-
    https://na.artifactory.swg-devops.com/artifactory/wiotp-generic-local/dependencies/wheels
  WHEELS: $GITHUB_WORKSPACE/build/install/
  ARTIFACTORY_TOKEN: '${{ secrets.ARTIFACTORY_TOKEN }}'
jobs:
  pre-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Initialise the build system
        run: |
          chmod u+x $GITHUB_WORKSPACE/build/bin/*.sh
          ls -lrt
          $GITHUB_WORKSPACE/build/bin/initbuild.sh
          source $GITHUB_WORKSPACE/build/bin/.functions.sh
      - name: downloads
        run: >
          wget --header="Authorization:Bearer "${{ secrets.ARTIFACTORY_TOKEN
          }}""
          "$WHEELS_URL/s390x/cryptography-42.0.0-cp311-cp311-linux_s390x.whl "
          -P ${{ github.workspace }}/image/install

          ls -lrt ${{ github.workspace }}/image/install
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cryptography-42.0.0-cp311-cp311-linux_s390x.whl
          path: >-
            ${{ github.workspace
            }}/image/install/cryptography-42.0.0-cp311-cp311-linux_s390x.whl
          github-token: '${{ secrets.GITHUB_TOKEN }}'
  download:
    needs: pre-builds
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: >-
            ${{ github.workspace
            }}/image/install/cryptography-42.0.0-cp311-cp311-linux_s390x.whl
          merge-multiple: true
      - run: >-
          ls -R ${{ github.workspace
          }}/image/install/cryptography-42.0.0-cp311-cp311-linux_s390x.whl